
spring:
  application:
    name: "gatewayserver"

  config:
    import: "optional:configserver:http://localhost:8071/"

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceID: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "accounts"
    description: "EastUnion Bank gatewayserver Application"
    version: "1.0.0"

logging:
  level:
    com:
      eastunion:
        gatewayserver: DEBUG
