
build:
    version: "3.0"

accounts:
  message: "Welcome to EastUnion Bank accounts related local APIs "
  contactDetails:
    name: "Kajal Koravi - Developer"
    email: "kajalkoravi@eastunion.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
